### ISSUE TITLE
ChromeDriver Instantiation issues in integration tests in github actions

### ISSUE THREAD

**Issue by dnyn92** [dequelabs/axe-core-nuget#198]
Hello,

First of all thanks for your great work on this package!

I am currently struggle to instantiate the ChromeDriver at this part `var webDriver = new ChromeDriver()` in my integration test in my github actions workflow. The exception that is thrown is while instantiating.

I assume that I am not installing the chrome webdriver the correct way on the github runner so that it can be used in my test environment. Can you tell me what is the correct way?

I have already tried out to add the installation of chrome and the webdriver in the workflow but this has not fixed my issue yet. I have used the following github actions: `browser-actions/setup-chrome@v1`, `nanasess/setup-chromedriver@v2`.

Happy for any kind of hints or support 🙏

**Comment by radmorecameron** [comment]
I am using Playwright instead of Selenium so I don't have all the answers but this might help:

- this project uses the WebDriverManager NuGet package to download drivers (and browsers?). I'd take a look at this file (I highlighted the line that uses WebDriverManager to download the driver/return the path of the driver. ChromeOptions has a BinaryPath property that should be set to the path of the driver): https://github.com/dequelabs/axe-core-nuget/blob/760c502ec7d035b8ac9da6b940c3775713b9fd04/packages/selenium/test/IntegrationTestBase.cs#L144 I believe SeleniumManager/DriverFinder is the new/official way of doing it now (this is part of the Selenium NuGet package)
- you might need to make sure that tests are ran headless in github actions https://github.com/dequelabs/axe-core-nuget/blob/760c502ec7d035b8ac9da6b940c3775713b9fd04/packages/selenium/test/IntegrationTestBase.cs#L96

**Comment by dnyn92** [comment]
> I am using Playwright instead of Selenium so I don't have all the answers but this might help:
> 
> * this project uses the WebDriverManager NuGet package to download drivers (and browsers?). I'd take a look at this file (I highlighted the line that uses WebDriverManager to download the driver/return the path of the driver. ChromeOptions has a BinaryPath property that should be set to the path of the driver): 
>     
>       
>         [axe-core-nuget/packages/selenium/test/IntegrationTestBase.cs](https://github.com/dequelabs/axe-core-nuget/blob/760c502ec7d035b8ac9da6b940c3775713b9fd04/packages/selenium/test/IntegrationTestBase.cs#L144)
>       
>       
>            Line 144
>         in
>         [760c502](/dequelabs/axe-core-nuget/commit/760c502ec7d035b8ac9da6b940c3775713b9fd04)
>       
>     
>     
>       
>   
>           
>             
>              return new DriverManager().SetUpDriver(driverManagerConfig); 
>           
>       
>     
>   
>    I believe SeleniumManager/DriverFinder is the new/official way of doing it now (this is part of the Selenium NuGet package)
> * you might need to make sure that tests are ran headless in github actions 
>     
>       
>         [axe-core-nuget/packages/selenium/test/IntegrationTestBase.cs](https://github.com/dequelabs/axe-core-nuget/blob/760c502ec7d035b8ac9da6b940c3775713b9fd04/packages/selenium/test/IntegrationTestBase.cs#L96)
>       
>       
>            Line 96
>         in
>         [760c502](/dequelabs/axe-core-nuget/commit/760c502ec7d035b8ac9da6b940c3775713b9fd04)
>       
>     
>     
>       
>   
>           
>             
>              chromeOptions.AddArgument("--headless");

Thanks for your hints, that helped me a lot! Setting to headless mode was one part of the solution.

I eventually got it to work with this workflow snippet
```
- name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 131
          install-chromedriver: true
```
What needs to be of course ensured is that the chromedriver version of the workflow is matching the one in the project.

EDIT: The solution is even easier. I was not aware that I have to also install `Selenium.WebDriver.ChromeDriver` in addition to `Selenium.WebDriver`. Now it works even without that chrome driver pipeline step
